project_id = "glzombobqywismnoqfrk"

[functions.generate-questions]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-schedule]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
